const SIDEBAR_HANDLE = 'SIDEBAR_HANDLE';
const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
const CONFIRMATION_OPEN = 'CONFIRMATION_OPEN';
const CONFIRMATION_CLOSE = 'CONFIRMATION_CLOSE';
const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

module.exports = {
  SIDEBAR_HANDLE,
  SIDEBAR_CLOSE,
  CONFIRMATION_OPEN,
  CONFIRMATION_CLOSE,
  START_LOADING,
  STOP_LOADING,
  OPEN_MODAL,
  CLOSE_MODAL
};
