const SET_ELECTION = 'SET_ELECTION';
const SET_CANDIDATES = 'SET_CANDIDATES';
const SET_VOTERS = 'SET_VOTERS';

const SET_COMMUNITY_USERS = 'SET_COMMUNITY_USERS';
const SET_COMMUNITY = 'SET_COMMUNITY';

const FETCH_ELECTION_DATA = 'FETCH_ELECTION_DATA';

module.exports = {
  SET_ELECTION,
  SET_CANDIDATES,
  SET_VOTERS,
  SET_COMMUNITY_USERS,
  SET_COMMUNITY,
  FETCH_ELECTION_DATA
};
