const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_LOAD = 'LOGIN_LOAD';
const LOGIN_FAILED = 'LOGIN_FAILED';

const LOGOUT_LOAD = 'LOGOUT_LOAD';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_LOAD = 'REGISTER_LOAD';
const REGISTER_FAILED = 'REGISTER_FAILED';

module.exports = {
  LOGIN_SUCCESS,
  LOGIN_LOAD,
  LOGIN_FAILED,
  REGISTER_SUCCESS,
  REGISTER_LOAD,
  REGISTER_FAILED,
  LOGOUT_LOAD,
  LOGOUT_SUCCESS
};